version: "3.3"

services:
  mytekmonitor_frontend:
    build:
      context: ./frontend
      dockerfile: ../dockerfiles/Dockerfile.front.dev
    environment:
      WDS_SOCKET_PORT: "5000"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  mytekmonitor_backend:
    build:
      context: ./backend
      dockerfile: ../dockerfiles/Dockerfile.back.dev
    restart: unless-stopped
    volumes:
      - ./backend/:/app/
      - ./env.js:/app/env.js

  my_tekmonitor_proxy:
    image: nginx:alpine
    links:
      - mytekmonitor_backend
      - mytekmonitor_frontend
    volumes:
      - ./dockerfiles/proxy.dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"