# stage1 - build react app first 
FROM node:16 as build

WORKDIR /app

COPY package.json ./
RUN npm install 
COPY . .
RUN npm run build

FROM nginx:1.19-alpine AS server
COPY ./config/web.nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build ./app/build /usr/share/nginx/html