FROM node:16

WORKDIR /app

COPY package.json .
COPY package-lock.json .

RUN npm install
RUN npm i -g nodemon
RUN mkdir -p node_modules/.cache && chmod -R 777 node_modules/.cache

CMD npm install && npm run dev